### ISSUE TITLE
Logic of the matrix explained?

### ISSUE THREAD

**Issue by stratis63** [AWSW-de/WordClock-16x16-LED-matrix#8]
Do you have the logic behind the 16x16 or 16x8 matrix explained?
if yes in which procedures.
I am trying to translate the source so it can drive a greek frontplate but I was thinkingbthatvthere must be a way to simplify the translation to other languages.
Just want to make sure I understood the logic behind it.

**Comment by AWSW-de** [comment]
Hello, 
the logic is not explained separately because when you can code you will understand it easily. If you cannot code it might not be possible because this is quiet a complex  project. 
As explained earlier I don’t have time to perform additional translation request currently and in near future. It takes me about 2 if not 3 days to create/add 1 new language on the front and the code, print and test it, so this is time consuming even it you know how to perform the steps. This is not a simple process as you say, because it all needs to fit together.
In addition the model files will not be shared so that the changes on the front will not be easy to do which have to fit to the code of course as well to make it work. 
Thanks for your understanding and please stop spamming me on all channels.
Kind regards.
